name: sentiment-analysis
channels:
  - conda-forge
dependencies:
  - python=3.9.10
  - pip:
    - mlflow==2.10.2
    - matplotlib==3.8.3
    - numpy==1.26.4
    - pandas==2.2.0
    - scikit-learn==1.4.1.post1
    